steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/voicemail-transcriber-repo/voicemail-transcriber',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/voicemail-transcriber-repo/voicemail-transcriber'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'voicemail-transcriber',
      '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/voicemail-transcriber-repo/voicemail-transcriber',
      '--region=europe-west1',
      '--platform=managed',
      '--execution-environment=gen2',
      '--allow-unauthenticated',
      '--service-account=voicemail-transcriber@voicemail-transcribe-454814.iam.gserviceaccount.com',
      '--cpu=1',
      '--memory=512Mi',
      '--min-instances=1',
      '--max-instances=10',
      '--port=8080',
      '--use-http2',
      '--timeout=300s',
      '--startup-cpu-boost',
      '--cpu-throttling',
      '--set-env-vars=^##^GCP_PROJECT_ID=voicemail-transcribe-454814##PUBSUB_TOPIC_NAME=projects/voicemail-transcribe-454814/topics/gmail-notifications##EMAIL_RESPONSE_ADDRESS=booking@jakatasalon.co.uk##PORT=8080',
      '--update-secrets=^##^DEEPGRAM_API_KEY=deepgram-api-key:latest##gmail-service-account=gmail-service-account:latest'
      '--ingress=all',
      '--startup-probe-path=/health',
      '--startup-probe-initial-delay=10s',
      '--startup-probe-period=5s',
      '--startup-probe-failure-threshold=3',
      '--startup-probe-timeout=5s',
      '--liveness-probe-path=/health',
      '--liveness-probe-period=30s',
      '--liveness-probe-timeout=5s',
      '--liveness-probe-failure-threshold=3',
      '--readiness-probe-path=/health',
      '--readiness-probe-period=30s',
      '--readiness-probe-timeout=5s',
      '--readiness-probe-failure-threshold=3'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true

timeout: '1200s'

substitutions:
  _REGION: 'europe-west1'
  _SERVICE_NAME: 'voicemail-transcriber'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/voicemail-transcriber-repo/voicemail-transcriber'