name: voicemailTranscriber
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/go:1.21'
    entrypoint: 'go'
    args: ['build', './cmd/server']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'functions',
        'deploy',
        'voicemailTranscriber',
        '--gen2',
        '--runtime=go121',
        '--entry-point=HandleRequest',
        '--region=europe-west1',
        '--trigger-http',
        '--allow-unauthenticated',
        '--set-env-vars=GCP_PROJECT_ID=...,PUBSUB_TOPIC_NAME=...,EMAIL_RESPONSE_ADDRESS=...'
      ]
