version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.jakata
    volumes:
      - ./secrets:/secrets:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/credentials.json